[package]
name = "cigale"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.11.0"
gdk-pixbuf = "0.7.0"
relm = "0.18.0"
relm-derive = "0.18.0"
chrono = "0.4"
git2 = "0.11.0"
pango = "0.7.0"


[dependencies.gtk]
version = "0.7.0"
features = ["v3_22_29"]
