[package]
name = "cigale"
version = "0.5.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.9.3"
gio = "0.8.1"
gdk = "0.12.1"
relm = "0.19.0"
relm-derive = "0.19.0"
chrono = {version="0.4" , features = ["serde"]}
git2 = "0.13.5"
pango = "0.8.0"
mailparse = "0.12.0"
toml = "0.5.6"
dirs = "2.0.2"
serde = "1.0"
serde_derive = "1.0"
scraper = "0.12.0"
reqwest = {version="0.10.4", features=["blocking", "cookies"]}
env_logger = "0.7.1"
log = "0.4.8"
regex = "1"
itertools = "0.9"
rayon = "1.3"
serde_json = "1.0"

[dependencies.ical]
version = "0.6.0"
default-features = false
features = ["ical"]

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22_29"]
