[package]
name = "cigale"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.12.0"
gdk-pixbuf = "0.8.0"
relm = "0.19.0"
relm-derive = "0.19.0"
chrono = "0.4"
git2 = "0.11.0"
pango = "0.8.0"
mailparse = "0.10.3"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_22_29"]
