[package]
name = "cigale"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.9.1"
gdk = "0.12.0"
gdk-pixbuf = "0.8.0"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_22"]

[dependencies.gio]
version = ""
features = ["v2_44"]
